repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        fail_fast: true
        language: python
        types: [python]
        language_version: python3.12
      - id: autoflake
        name: autoflake
        entry: autoflake
        fail_fast: true
        language: python
      - id: isort
        name: isort
        entry: isort
        fail_fast: true
        language: python
      - id: prospector
        name: prospector
        entry: prospector
        language: python