name: base-project-local-dev-environment
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: postgres
      POSTGRES_DB: basedb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: